version: '3.8'

services:
  db_postgres:
    image: postgres
    container_name: db_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/data/postgres
    ports:
      - 54320:5432
  app:
    build: .
    container_name: api_golang
    volumes: 
      - .:/go/src/
    depends_on:
      - db_postgres

volumes:
  pgdata: