version: '3.8'

services:
  db_postgres:
    image: postgres:13.2
    container_name: db_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: api_golang
    volumes: 
      - .:/go/src/
    depends_on:
      - db_postgres

volumes:
  pgdata: